### ISSUE TITLE
Link para a imagem do courseware está quebrado

### ISSUE THREAD

**Issue by ricardoebbers** [IF977/if977#1]
No final do arquivo disponível em [courseware.md](https://github.com/IF977/if977/blob/master/pages/courseware.md) o link para [saasbook-0.10.3.1.zip](http://dekr0bcnl4w2b.cloudfront.net/saasbook-0.10.3.1.zip) retorna uma página de erro NoSuchBucket.

**Comment by vinicius3w** [comment]
Obrigado! Corrigi colocando um link para uma página que ensina como montar uma VM para o meso fim, a partir de uma imagem Ubuntu. A imagem do curso já não é mais oficialmente suportada.
